[metadata]
universe-id = 1234
discount-prefix = "ðŸ’²{}% OFFðŸ’² "
luau-file = "products.luau"
name-filters = []


#################################################################
#    _____                                                      #
#   / ____|                                                     #
#  | |  __  __ _ _ __ ___   ___ _ __   __ _ ___ ___  ___  ___   #
#  | | |_ |/ _` | '_ ` _ \ / _ \ '_ \ / _` / __/ __|/ _ \/ __|  #
#  | |__| | (_| | | | | | |  __/ |_) | (_| \__ \__ \  __/\__ \  #
#   \_____|\__,_|_| |_| |_|\___| .__/ \__,_|___/___/\___||___/  #
#                              | |                              #
#                              |_|                              #
#################################################################

[gamepasses."ab"]
id = 0
price = 0
discount = 0
active = true

[gamepasses."abc"]
id = 0
price = 0
discount = 0
active = true

[gamepasses."ac"]
id = 0
price = 0
discount = 0
active = true


################################################
#   _____               _            _         #
#  |  __ \             | |          | |        #
#  | |__) | __ ___   __| |_   _  ___| |_ ___   #
#  |  ___/ '__/ _ \ / _` | | | |/ __| __/ __|  #
#  | |   | | | (_) | (_| | |_| | (__| |_\__ \  #
#  |_|   |_|  \___/ \__,_|\__,_|\___|\__|___/  #
################################################


[products."a"]
id = 0
name = "product-name"
description = "Description of the product-name."
price = 0
active = true
discount = 0

[products."b"]
name = "product-name"
id = 0
price = 0
active = true
discount = 0

[products."c"]
name = "product-name"
id = 0
price = 0
active = true
discount = 0

[products."d"]
name = "product-name"
id = 0
price = 0
discount = 0
active = true

[products."e"]
name = "product-name"
id = 0
price = 0
discount = 0
active = true
